In [33]:
import numpy as np
from sklearn.impute import SimpleImputer


train_data = [[7, 6, 5],
              [4, np.nan, 5],
              [1, 20, 8]]



# Create the SimpleImputer
imputer = SimpleImputer(strategy='mean')

# Fit the imputer #on the training data
imputer.fit(train_data)

# Print the statistics_
print("Statistics from SimpleImputer:", imputer.statistics_)

# Calculate the mean using np.nanmean
nanmean_values = np.nanmean(train_data, axis=0)
print("Mean using np.nanmean:", nanmean_values)

Statistics from SimpleImputer: [ 4. 13.  6.]
Mean using np.nanmean: [ 4. 13.  6.]


In [34]:
#2
train_imput = imputer.transform(train_data)
print(train_imput)

[[ 7.  6.  5.]
 [ 4. 13.  5.]
 [ 1. 20.  8.]]


In [35]:
#3
test_data = [[np.nan, 1, 2],
             [7, np.nan, 9],
             [np.nan, 2, 4]]


test_data_imputed = imputer.transform(test_data)

print(test_data_imputed)

[[ 4.  1.  2.]
 [ 7. 13.  9.]
 [ 4.  2.  4.]]
