In [4]:
#Exercise 2
import numpy as np
from sklearn.preprocessing import StandardScaler

X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

mean_scaled = np.mean(X_train_scaled, axis=0)
std_scaled = np.std(X_train_scaled, axis=0)


print("Moyenne (après mise à l'échelle):", mean_scaled)
print("Écart type (après mise à l'échelle):", std_scaled)
print("X_train_scaled:\n", X_train_scaled)


Moyenne (après mise à l'échelle): [0. 0. 0.]
Écart type (après mise à l'échelle): [1. 1. 1.]
X_train_scaled:
 [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [5]:
#2
X_test = np.array([[ 2., -1.,  1.],
                     [ 3.,  3.,  -1.],
                     [ 1.,  1., 1.]])

X_test_scaled = scaler.transform(X_test)

print("Scaled Test Data:")
print(X_test_scaled)

Scaled Test Data:
[[ 1.22474487 -1.22474487  0.53452248]
 [ 2.44948974  3.67423461 -1.06904497]
 [ 0.          1.22474487  0.53452248]]
